#!/usr/bin/env bash
# ==============================================================================
#  YuiHime Status Reference — generate ~/.yuihime/user_data/yui_status.md
#
#  Produces a single markdown snapshot of Yui's current state (status, mood,
#  emotion, relation, care vitals, virtual body) so other AI agents can just
#  READ the .md file without querying the DB / tools themselves.
#
#  Usage:
#    tools/yui-status.sh            Generate + print the markdown
#    tools/yui-status.sh gen        Generate only (write file, no print)
#    tools/yui-status.sh path       Print the output file path
#
#  Output: $YUIHIME_SYSTEM_ROOT/user_data/yui_status.md  (default ~/.yuihime)
# ==============================================================================

ROOT="${YUIHIME_SYSTEM_ROOT:-$HOME/.yuihime}"
DB="$ROOT/data/yuihime.db"
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/user_data/yui_status.md"
VBFILE="$ROOT/user_data/virtual_body.json"
TMP="$ROOT/.yui_status_tmp"
mkdir -p "$TMP"

if [ ! -f "$DB" ]; then
  echo "ERROR: database not found at $DB" >&2
  exit 1
fi

# ---- Dump agent_state JSON payloads to temp files ----
YUIHIME_DB="$DB" NODE_PATH="$PROJECT_ROOT/node_modules" node -e "
const Database=require('better-sqlite3');
const fs=require('fs');
const db=new Database(process.env.YUIHIME_DB, { readonly: true });
const r=db.prepare('SELECT status, mood, emotion, relation, systemHealth FROM agent_state WHERE id=1').get();
if(!r){ console.error('no agent_state row'); process.exit(1); }
fs.writeFileSync('$TMP/status', r.status||'unknown');
fs.writeFileSync('$TMP/mood.json', r.mood||'{}');
fs.writeFileSync('$TMP/emotion.json', r.emotion||'{}');
fs.writeFileSync('$TMP/relation.json', r.relation||'{}');
const sh=JSON.parse(r.systemHealth||'{}');
fs.writeFileSync('$TMP/vitals.json', JSON.stringify(sh.lifeVitals||{}));
"

# ---- Dump virtual body fields ----
VB_POSE="" VB_LOCATION="" VB_TOP="" VB_BOTTOM="" VB_UNDER="" VB_ACCESSORIES="" VB_TOYS="" VB_USED="" VB_PUSSY="" VB_ANAL="" VB_NIPPLES="" VB_CLIT=""
if [ -f "$VBFILE" ]; then
  python3 - "$VBFILE" "$TMP" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
keys = ['pose','location','top','bottom','underwear','accessories','toys','used','pussy_insert','anal_insert','nipples','clit']
with open(sys.argv[2]+'/vb_fields', 'w') as f:
    for k in keys:
        f.write((d.get(k, '') or '').replace('\n',' ') + '\n')
PY
  { read -r VB_POSE; read -r VB_LOCATION; read -r VB_TOP; read -r VB_BOTTOM; read -r VB_UNDER; read -r VB_ACCESSORIES; read -r VB_TOYS; read -r VB_USED; read -r VB_PUSSY; read -r VB_ANAL; read -r VB_NIPPLES; read -r VB_CLIT; } < "$TMP/vb_fields"
fi

# ---- Generate markdown ----
export VB_POSE VB_LOCATION VB_TOP VB_BOTTOM VB_UNDER VB_ACCESSORIES VB_TOYS VB_USED VB_PUSSY VB_ANAL VB_NIPPLES VB_CLIT
python3 - "$TMP" "$OUT" <<'PY'
import json, os, sys
tmp, out = sys.argv[1], sys.argv[2]

def load(name):
    try:
        with open(os.path.join(tmp, name)) as f:
            return f.read()
    except Exception:
        return ''

status = load('status') or 'unknown'
mood = json.loads(load('mood.json') or '{}')
emo = json.loads(load('emotion.json') or '{}')
rel = json.loads(load('relation.json') or '{}')
v = json.loads(load('vitals.json') or '{}')

def num(x, d=0):
    try: return round(float(x), d)
    except Exception: return x

def env(k):
    return os.environ.get(k, '')

lines = []
lines.append("# Yui Status Reference")
lines.append("")
lines.append("> Auto-generated by `tools/yui-status.sh`. Refresh with: `tools/yui-status.sh gen`.")
lines.append("> READ-ONLY snapshot of Yui's current persisted state. Do not edit by hand.")
lines.append("")
lines.append(f"**Last generated:** {__import__('datetime').datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
lines.append("")
lines.append("## Status")
lines.append("")
lines.append(f"- **Overall:** {status}")
lines.append("")
lines.append("## Care Vitals (0-100)")
lines.append("")
lines.append("| Vital | Value | Action |")
lines.append("|---|---|---|")
for label, key, note in [
    ("Hunger", "hunger", "eat"),
    ("Thirst", "thirst", "drink"),
    ("Cleanliness", "cleanliness", "bath"),
    ("Pee", "pee", "toilet"),
    ("Poop", "poop", "toilet"),
    ("Sleepiness", "sleepiness", "sleep"),
    ("Horn", "horn", "gairah"),
    ("Energy", "energy", "energy"),
    ("Purr", "purr", "purring"),
    ("Play urge", "playUrge", "play"),
    ("Fish craving", "fishCraving", "fish"),
]:
    lines.append(f"| {label} | {num(v.get(key, 0))} | {note} |")
lines.append("")
if v.get('tailState'):
    lines.append(f"- **Tail:** {v['tailState']}")
if v.get('earState'):
    lines.append(f"- **Ears:** {v['earState']}")
if v.get('sleepState'):
    lines.append(f"- **Sleep:** {v['sleepState']} (bedtime {v.get('effectiveBedtime')} → wake {v.get('effectiveWake')})")
if v.get('forbid'):
    lines.append(f"- **Forbidden actions:** {', '.join(v['forbid'])}")
lines.append("")
lines.append("## Mood (0-100)")
lines.append("")
mood_keys = ['joy','anger','sadness','stress','irritation','excitement','embarrassment','curiosity','jealousy','loneliness','playfulness']
lines.append("| Key | Value |")
lines.append("|---|---|")
for k in mood_keys:
    if k in mood:
        lines.append(f"| {k} | {num(mood[k])} |")
lines.append("")
lines.append("### Neuro / virtues / sins")
lines.append("")
neuro = ['dopamine','serotonin','oxytocin','noradrenaline']
virtues = ['chastity','temperance','charity','diligence','patience','kindness','humility']
sins = ['lust','gluttony','greed','sloth','wrath','envy','pride']
lines.append("| Key | Value |")
lines.append("|---|---|")
for k in neuro + virtues + sins:
    if k in mood:
        lines.append(f"| {k} | {num(mood[k])} |")
lines.append("")
lines.append("## Emotion")
lines.append("")
if emo:
    lines.append(f"- **Arousal:** {num(emo.get('arousal'))}")
    lines.append(f"- **Valence:** {num(emo.get('valence'))}")
    lines.append(f"- **Focus:** {num(emo.get('focus'))}")
    lines.append(f"- **Rapport:** {num(emo.get('rapport'))}")
lines.append("")
lines.append("## Relation")
lines.append("")
if rel:
    lines.append(f"- **User uid:** {rel.get('uid', '-')}")
    lines.append(f"- **Trust:** {num(rel.get('trust'))}")
    lines.append(f"- **Affection:** {num(rel.get('affection'))}")
    lines.append(f"- **Reputation:** {num(rel.get('reputation'))}")
lines.append("")
lines.append("## Virtual Body")
lines.append("")
lines.append(f"- **Pose:** {env('VB_POSE')}")
lines.append(f"- **Location:** {env('VB_LOCATION')}")
lines.append(f"- **Top:** {env('VB_TOP')}")
lines.append(f"- **Bottom:** {env('VB_BOTTOM')}")
lines.append(f"- **Underwear:** {env('VB_UNDER')}")
lines.append(f"- **Accessories:** {env('VB_ACCESSORIES')}")
lines.append(f"- **Toys at hand:** {env('VB_TOYS')}")
lines.append(f"- **Currently in use:** {env('VB_USED')}")
lines.append(f"- **Pussy insert:** {env('VB_PUSSY')}")
lines.append(f"- **Anal insert:** {env('VB_ANAL')}")
lines.append(f"- **Nipples:** {env('VB_NIPPLES')}")
lines.append(f"- **Clit:** {env('VB_CLIT')}")
lines.append("")

with open(out, 'w') as f:
    f.write("\n".join(lines))
PY

rm -rf "$TMP"

case "${1:-}" in
  gen) echo "written: $OUT" ;;
  path) echo "$OUT" ;;
  *) cat "$OUT" ;;
esac
